import { SEO_INSTRUCTIONS } from './instructions';

export const EXHAUSTIVE_CHECKS = [
    { id: 'google_index', category: 'Indexing', title: 'Google index status', suggestion: 'Ensure your site is indexable by Google.', howToFix: SEO_INSTRUCTIONS.google_index },
    { id: 'analytics', category: 'Analytics', title: 'Google Web Analytics', suggestion: 'Connect Google Analytics to track visitors.', howToFix: SEO_INSTRUCTIONS.analytics },
    { id: 'speed', category: 'Performance', title: 'Site Loading Speed Test', suggestion: 'Optimize assets to load under 2.5s.', howToFix: SEO_INSTRUCTIONS.speed },
    { id: 'robots', category: 'Indexing', title: 'Robots File', suggestion: 'Provide a valid robots.txt file.', howToFix: SEO_INSTRUCTIONS.robots },
    { id: 'sitemap', category: 'Indexing', title: 'HTML Sitemap', suggestion: 'Include an HTML sitemap for easier navigation.', howToFix: SEO_INSTRUCTIONS.sitemap },
    { id: 'friendly_url', category: 'Structure', title: 'Friendly URLs', suggestion: 'Use descriptive, keyword-rich URLs.', howToFix: SEO_INSTRUCTIONS.friendly_url },
    { id: 'broken_links', category: 'Structure', title: 'Broken Links', suggestion: 'Fix or remove any 404 links on the page.', howToFix: SEO_INSTRUCTIONS.broken_links },
    { id: 'meta_desc', category: 'Content', title: 'Meta Description', suggestion: 'Provide unique meta descriptions.', howToFix: SEO_INSTRUCTIONS.meta_desc },
    { id: 'meta_title', category: 'Content', title: 'Meta Title', suggestion: 'Ensure titles are unique and under 60 chars.', howToFix: SEO_INSTRUCTIONS.meta_title },
    { id: 'keywords', category: 'Content', title: 'Keywords', suggestion: 'Optimize for primary and secondary keywords.', howToFix: SEO_INSTRUCTIONS.keywords },
    { id: 'duplicate', category: 'Content', title: 'Duplicate Content', suggestion: 'Avoid exact duplicate content across pages.', howToFix: SEO_INSTRUCTIONS.duplicate },
    { id: 'canonical', category: 'Structure', title: 'URL Canonicalization Test', suggestion: 'Set canonical tags to prevent duplicate indexing.', howToFix: SEO_INSTRUCTIONS.canonical },
    { id: 'alt_tags', category: 'Media', title: 'Image Alt Tag Missing', suggestion: 'Add descriptive ALT text to all images.', howToFix: SEO_INSTRUCTIONS.alt_tags },
    { id: 'responsive_img', category: 'Media', title: 'Responsive Image Test', suggestion: 'Serve appropriately sized images.', howToFix: SEO_INSTRUCTIONS.responsive_img },
    { id: 'modern_img', category: 'Media', title: 'Modern Image Format Test', suggestion: 'Use WebP or AVIF image formats.', howToFix: SEO_INSTRUCTIONS.modern_img },
    { id: 'img_alt_check', category: 'Media', title: 'Detailed Image Alt Audit', suggestion: 'Ensure all images have valid alt attributes for accessibility and SEO.', howToFix: SEO_INSTRUCTIONS.img_alt_check },
    { id: 'inline_css', category: 'Code', title: 'Inline CSS Test', suggestion: 'Move inline CSS to external stylesheets.', howToFix: SEO_INSTRUCTIONS.inline_css },
    { id: 'deprecated_html', category: 'Code', title: 'Deprecated HTML Tags Test', suggestion: 'Remove older tags like <font> or <center>.', howToFix: SEO_INSTRUCTIONS.deprecated_html },
    { id: 'css_minification', category: 'Code', title: 'CSS Minification Test', suggestion: 'Minify CSS files to reduce size.', howToFix: SEO_INSTRUCTIONS.css_minification },
    { id: 'lcp', category: 'Performance', title: 'Largest Contentful Paint Test', suggestion: 'Optimize the largest element to load quickly.', howToFix: SEO_INSTRUCTIONS.lcp },
    { id: 'cls', category: 'Performance', title: 'Cumulative Layout Shift Test', suggestion: 'Specify dimensions for media to prevent shifts.', howToFix: SEO_INSTRUCTIONS.cls },
    { id: 'h1_tags', category: 'Content', title: 'Heading H1 Tags Test', suggestion: 'Use exactly one H1 tag per page.', howToFix: SEO_INSTRUCTIONS.h1_tags },
    { id: 'h2_tags', category: 'Content', title: 'Heading H2 Tags Test', suggestion: 'Use H2 tags to structure content.', howToFix: SEO_INSTRUCTIONS.h2_tags },
    { id: 'html_size', category: 'Code', title: 'HTML Page Size Test', suggestion: 'Keep total HTML size reasonable.', howToFix: SEO_INSTRUCTIONS.html_size },
    { id: 'img_caching', category: 'Performance', title: 'Image Caching Test', suggestion: 'Set long cache TTL for images.', howToFix: SEO_INSTRUCTIONS.img_caching },
    { id: 'js_caching', category: 'Performance', title: 'JavaScript Caching Test', suggestion: 'Set long cache TTL for JS.', howToFix: SEO_INSTRUCTIONS.js_caching },
    { id: 'css_caching', category: 'Performance', title: 'CSS Caching Test', suggestion: 'Set long cache TTL for CSS.', howToFix: SEO_INSTRUCTIONS.css_caching },
    { id: 'error_404', category: 'Structure', title: 'Custom 404 Error Page Test', suggestion: 'Create a helpful custom 404 page.', howToFix: SEO_INSTRUCTIONS.error_404 },
    { id: 'nofollow', category: 'Structure', title: 'Nofollow Tag Test', suggestion: 'Use nofollow for untrusted outbound links.', howToFix: SEO_INSTRUCTIONS.nofollow },
    { id: 'favicon', category: 'Structure', title: 'Favicon Test', suggestion: 'Provide a valid favicon.', howToFix: SEO_INSTRUCTIONS.favicon }
];
