export const SEO_INSTRUCTIONS: Record<string, string> = {
    google_index: 'Check robots.txt for "Disallow: /" and ensure the <meta name="robots" content="noindex"> tag is removed.',
    analytics: 'Install the Google Tag (gtag.js) in the <head> of your website pages.',
    speed: 'Compress images, minify CSS/JS files, and use a Content Delivery Network (CDN).',
    robots: 'Create a robots.txt file at your domain root (e.g., example.com/robots.txt) declaring crawl rules.',
    sitemap: 'Generate an XML sitemap and reference it in your robots.txt or submit it via Search Console.',
    friendly_url: 'Avoid dynamic parameters like "?id=123"; use human-readable slugs like "/seo-tips".',
    broken_links: 'Check for typos in your <a> tags and update any links pointing to deleted pages.',
    meta_desc: 'Add a <meta name="description" content="..."> tag between 120-160 characters.',
    meta_title: 'Update the <title> tag to be unique and include your primary keyword at the beginning.',
    keywords: 'Naturally integrate keywords into headings (H1, H2), meta descriptions, and the first paragraph.',
    duplicate: 'Use canonical tags or 301 redirects to point at the original source of the content.',
    canonical: 'Add a <link rel="canonical" href="..."> tag to tell search engines which URL is the preferred version.',
    alt_tags: 'Ensure every <img> tag has an alt="Description" attribute for accessibility and SEO.',
    responsive_img: 'Use "srcset" and "sizes" attributes or modern CSS (object-fit) to ensure images adapt to screen sizes.',
    modern_img: 'Convert JPEG/PNG images to WebP or AVIF for better compression without quality loss.',
    img_alt_check: 'Audit your code for <img> tags with missing alt attributes and add meaningful descriptions.',
    inline_css: 'Remove style="..." attributes from HTML elements and place them in an external .css file.',
    deprecated_html: 'Replace old tags with modern semantic HTML and CSS (e.g., use <div> with text-align: center instead of <center>).',
    css_minification: 'Use tools like PurgeCSS or CSSNano to remove whitespace and unused styles from your production CSS.',
    lcp: 'Prioritize loading the hero image or largest text block. Use font-display: swap and preconnect to important origins.',
    cls: 'Always include width and height attributes on images and video elements to reserve space.',
    h1_tags: 'Ensure there is only one <h1> tag and it contains the main topic of your page.',
    h2_tags: 'Divide your content into logical sections using <h2> subheadings.',
    html_size: 'Clean up unnecessary code, comments, and compress your HTML delivery using Gzip or Brotli.',
    img_caching: 'Set Cache-Control headers to at least 6 months (max-age=15552000) for static image assets.',
    js_caching: 'Set Cache-Control headers for JS files to max-age=31536000 (1 year) for better repeat performance.',
    css_caching: 'Configure your server to send "Cache-Control: public, max-age=31536000" for all CSS files.',
    error_404: 'Design a user-friendly 404.html page that includes a search bar and links to your homepage.',
    nofollow: 'Add rel="nofollow" to any external links that you don\'t want to pass "link juice" to.',
    favicon: 'Add a <link rel="icon" href="/favicon.ico"> to your <head> section.'
};
