export interface Country {
    code: string;
    name: string;
    flag: string;
    gl: string;
}

export const COUNTRIES: Country[] = [
    { code: 'US', name: 'United States', flag: '🇺🇸', gl: 'us' },
    { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', gl: 'uk' },
    { code: 'CA', name: 'Canada', flag: '🇨🇦', gl: 'ca' },
    { code: 'AU', name: 'Australia', flag: '🇦🇺', gl: 'au' },
    { code: 'DE', name: 'Germany', flag: '🇩🇪', gl: 'de' },
    { code: 'FR', name: 'France', flag: '🇫🇷', gl: 'fr' },
    { code: 'IN', name: 'India', flag: '🇮🇳', gl: 'in' },
    { code: 'BR', name: 'Brazil', flag: '🇧🇷', gl: 'br' },
    { code: 'JP', name: 'Japan', flag: '🇯🇵', gl: 'jp' },
    { code: 'ES', name: 'Spain', flag: '🇪🇸', gl: 'es' },
    { code: 'IT', name: 'Italy', flag: '🇮🇹', gl: 'it' },
    { code: 'RU', name: 'Russia', flag: '🇷🇺', gl: 'ru' },
    { code: 'MX', name: 'Mexico', flag: '🇲🇽', gl: 'mx' },
    { code: 'KR', name: 'South Korea', flag: '🇰🇷', gl: 'kr' },
    { code: 'ID', name: 'Indonesia', flag: '🇮🇩', gl: 'id' },
    { code: 'TR', name: 'Turkey', flag: '🇹🇷', gl: 'tr' },
    { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦', gl: 'sa' },
    { code: 'AF', name: 'Afghanistan', flag: '🇦🇫', gl: 'af' },
    { code: 'AL', name: 'Albania', flag: '🇦🇱', gl: 'al' },
    { code: 'DZ', name: 'Algeria', flag: '🇩🇿', gl: 'dz' },
    { code: 'AD', name: 'Andorra', flag: '🇦🇩', gl: 'ad' },
    { code: 'AO', name: 'Angola', flag: '🇦🇴', gl: 'ao' },
    { code: 'AR', name: 'Argentina', flag: '🇦🇷', gl: 'ar' },
    { code: 'AM', name: 'Armenia', flag: '🇦🇲', gl: 'am' },
    { code: 'AT', name: 'Austria', flag: '🇦🇹', gl: 'at' },
    { code: 'AZ', name: 'Azerbaijan', flag: '🇦🇿', gl: 'az' },
    { code: 'BS', name: 'Bahamas', flag: '🇧🇸', gl: 'bs' },
    { code: 'BH', name: 'Bahrain', flag: '🇧🇭', gl: 'bh' },
    { code: 'BD', name: 'Bangladesh', flag: '🇧🇩', gl: 'bd' },
    { code: 'BE', name: 'Belgium', flag: '🇧🇪', gl: 'be' },
    { code: 'BZ', name: 'Belize', flag: '🇧🇿', gl: 'bz' },
    { code: 'BJ', name: 'Benin', flag: '🇧🇯', gl: 'bj' },
    { code: 'BT', name: 'Bhutan', flag: '🇧🇹', gl: 'bt' },
    { code: 'BO', name: 'Bolivia', flag: '🇧🇴', gl: 'bo' },
    { code: 'BW', name: 'Botswana', flag: '🇧🇼', gl: 'bw' },
    { code: 'BG', name: 'Bulgaria', flag: '🇧🇬', gl: 'bg' },
    { code: 'KH', name: 'Cambodia', flag: '🇰🇭', gl: 'kh' },
    { code: 'CM', name: 'Cameroon', flag: '🇨🇲', gl: 'cm' },
    { code: 'CL', name: 'Chile', flag: '🇨🇱', gl: 'cl' },
    { code: 'CN', name: 'China', flag: '🇨🇳', gl: 'cn' },
    { code: 'CO', name: 'Colombia', flag: '🇨🇴', gl: 'co' },
    { code: 'CR', name: 'Costa Rica', flag: '🇨🇷', gl: 'cr' },
    { code: 'HR', name: 'Croatia', flag: '🇭🇷', gl: 'hr' },
    { code: 'CU', name: 'Cuba', flag: '🇨🇺', gl: 'cu' },
    { code: 'CY', name: 'Cyprus', flag: '🇨🇾', gl: 'cy' },
    { code: 'CZ', name: 'Czech Republic', flag: '🇨🇿', gl: 'cz' },
    { code: 'DK', name: 'Denmark', flag: '🇩🇰', gl: 'dk' },
    { code: 'DO', name: 'Dominican Republic', flag: '🇩🇴', gl: 'do' },
    { code: 'EC', name: 'Ecuador', flag: '🇪🇨', gl: 'ec' },
    { code: 'EG', name: 'Egypt', flag: '🇪🇬', gl: 'eg' },
    { code: 'EE', name: 'Estonia', flag: '🇪🇪', gl: 'ee' },
    { code: 'ET', name: 'Ethiopia', flag: '🇪🇹', gl: 'et' },
    { code: 'FI', name: 'Finland', flag: '🇫🇮', gl: 'fi' },
    { code: 'GR', name: 'Greece', flag: '🇬🇷', gl: 'gr' },
    { code: 'GT', name: 'Guatemala', flag: '🇬🇹', gl: 'gt' },
    { code: 'HN', name: 'Honduras', flag: '🇭🇳', gl: 'hn' },
    { code: 'HK', name: 'Hong Kong', flag: '🇭🇰', gl: 'hk' },
    { code: 'HU', name: 'Hungary', flag: '🇭🇺', gl: 'hu' },
    { code: 'IS', name: 'Iceland', flag: '🇮🇸', gl: 'is' },
    { code: 'IR', name: 'Iran', flag: '🇮🇷', gl: 'ir' },
    { code: 'IQ', name: 'Iraq', flag: '🇮🇶', gl: 'iq' },
    { code: 'IE', name: 'Ireland', flag: '🇮🇪', gl: 'ie' },
    { code: 'IL', name: 'Israel', flag: '🇮🇱', gl: 'il' },
    { code: 'JM', name: 'Jamaica', flag: '🇯🇲', gl: 'jm' },
    { code: 'JO', name: 'Jordan', flag: '🇯🇴', gl: 'jo' },
    { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿', gl: 'kz' },
    { code: 'KE', name: 'Kenya', flag: '🇰🇪', gl: 'ke' },
    { code: 'KW', name: 'Kuwait', flag: '🇰🇼', gl: 'kw' },
    { code: 'LV', name: 'Latvia', flag: '🇱🇻', gl: 'lv' },
    { code: 'LB', name: 'Lebanon', flag: '🇱🇧', gl: 'lb' },
    { code: 'LY', name: 'Libya', flag: '🇱🇾', gl: 'ly' },
    { code: 'LT', name: 'Lithuania', flag: '🇱🇹', gl: 'lt' },
    { code: 'LU', name: 'Luxembourg', flag: '🇱🇺', gl: 'lu' },
    { code: 'MY', name: 'Malaysia', flag: '🇲🇾', gl: 'my' },
    { code: 'MT', name: 'Malta', flag: '🇲🇹', gl: 'mt' },
    { code: 'MA', name: 'Morocco', flag: '🇲🇦', gl: 'ma' },
    { code: 'MM', name: 'Myanmar', flag: '🇲🇲', gl: 'mm' },
    { code: 'NP', name: 'Nepal', flag: '🇳🇵', gl: 'np' },
    { code: 'NL', name: 'Netherlands', flag: '🇳🇱', gl: 'nl' },
    { code: 'NZ', name: 'New Zealand', flag: '🇳🇿', gl: 'nz' },
    { code: 'NI', name: 'Nicaragua', flag: '🇳🇮', gl: 'ni' },
    { code: 'NG', name: 'Nigeria', flag: '🇳🇬', gl: 'ng' },
    { code: 'NO', name: 'Norway', flag: '🇳🇴', gl: 'no' },
    { code: 'OM', name: 'Oman', flag: '🇴🇲', gl: 'om' },
    { code: 'PK', name: 'Pakistan', flag: '🇵🇰', gl: 'pk' },
    { code: 'PA', name: 'Panama', flag: '🇵🇦', gl: 'pa' },
    { code: 'PY', name: 'Paraguay', flag: '🇵🇾', gl: 'py' },
    { code: 'PE', name: 'Peru', flag: '🇵🇪', gl: 'pe' },
    { code: 'PH', name: 'Philippines', flag: '🇵🇭', gl: 'ph' },
    { code: 'PL', name: 'Poland', flag: '🇵🇱', gl: 'pl' },
    { code: 'PT', name: 'Portugal', flag: '🇵🇹', gl: 'pt' },
    { code: 'QA', name: 'Qatar', flag: '🇶🇦', gl: 'qa' },
    { code: 'RO', name: 'Romania', flag: '🇷🇴', gl: 'ro' },
    { code: 'SG', name: 'Singapore', flag: '🇸🇬', gl: 'sg' },
    { code: 'SK', name: 'Slovakia', flag: '🇸🇰', gl: 'sk' },
    { code: 'SI', name: 'Slovenia', flag: '🇸🇮', gl: 'si' },
    { code: 'ZA', name: 'South Africa', flag: '🇿🇦', gl: 'za' },
    { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰', gl: 'lk' },
    { code: 'SE', name: 'Sweden', flag: '🇸🇪', gl: 'se' },
    { code: 'CH', name: 'Switzerland', flag: '🇨🇭', gl: 'ch' },
    { code: 'SY', name: 'Syria', flag: '🇸🇾', gl: 'sy' },
    { code: 'TW', name: 'Taiwan', flag: '🇹🇼', gl: 'tw' },
    { code: 'TH', name: 'Thailand', flag: '🇹🇭', gl: 'th' },
    { code: 'TN', name: 'Tunisia', flag: '🇹🇳', gl: 'tn' },
    { code: 'UA', name: 'Ukraine', flag: '🇺🇦', gl: 'ua' },
    { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪', gl: 'ae' },
    { code: 'UY', name: 'Uruguay', flag: '🇺🇾', gl: 'uy' },
    { code: 'UZ', name: 'Uzbekistan', flag: '🇺🇿', gl: 'uz' },
    { code: 'VE', name: 'Venezuela', flag: '🇻🇪', gl: 've' },
    { code: 'VN', name: 'Vietnam', flag: '🇻🇳', gl: 'vn' }
];
